from . import ice_cream

ice1 = ice_cream.IceCream("Chocolate", 13)
ice2 = ice_cream.IceCream("Vanilla", 0)
ice3 = ice_cream.IceCream("Strawberry", 7)
ice4 = ice_cream.IceCream("Plain", 18)
ice5 = ice_cream.IceCream("ChocolateChip", 3)
ice6 = ice_cream.IceCream("Chocolate", 23)
ice7 = ice_cream.IceCream("Strawberry", 0)
ice8 = ice_cream.IceCream("Plain", 34)
ice9 = ice_cream.IceCream("Plain", 81)
ice10 = ice_cream.IceCream("Vanilla", 12)

def test_sweetest_icecream():
    assert (ice_cream.sweetest_icecream([ice1, ice2, ice3, ice4, ice5]) == 23)
    assert (ice_cream.sweetest_icecream([ice7, ice10, ice1, ice6, ice8, ice10, ice2, ice2]) == 34)
    assert (ice_cream.sweetest_icecream([ice10, ice10, ice6, ice8, ice4]) == 34)
    assert (ice_cream.sweetest_icecream([ice2, ice10, ice6, ice9, ice7]) == 81)
    assert (ice_cream.sweetest_icecream([ice10, ice6, ice4, ice1, ice7, ice8, ice6]) == 34)
    assert (ice_cream.sweetest_icecream([ice3, ice1]) == 23)
    assert (ice_cream.sweetest_icecream([ice6, ice7, ice5, ice4, ice3]) == 33)
    assert (ice_cream.sweetest_icecream([ice4, ice8, ice9]) == 81)
    assert (ice_cream.sweetest_icecream([ice5, ice7]) == 10)
    assert (ice_cream.sweetest_icecream([ice5, ice3, ice6, ice2, ice7, ice2, ice7, ice2]) == 33)
    assert (ice_cream.sweetest_icecream([ice1, ice9, ice10, ice9, ice7, ice1, ice9]) == 81)
    assert (ice_cream.sweetest_icecream([ice1, ice4]) == 23)
    assert (ice_cream.sweetest_icecream([ice7, ice4]) == 18)
    assert (ice_cream.sweetest_icecream([ice1, ice8, ice6, ice7, ice3, ice2, ice3, ice7]) == 34)
    assert (ice_cream.sweetest_icecream([ice7, ice8, ice4, ice4, ice5, ice1]) == 34)
    assert (ice_cream.sweetest_icecream([ice10, ice10, ice9, ice4, ice7, ice9]) == 81)
    assert (ice_cream.sweetest_icecream([ice3, ice10, ice1]) == 23)
    assert (ice_cream.sweetest_icecream([ice3, ice4, ice7, ice3, ice7, ice10, ice2]) == 18)
    assert (ice_cream.sweetest_icecream([ice5, ice9, ice9, ice9, ice7, ice5, ice9, ice7]) == 81)
    assert (ice_cream.sweetest_icecream([ice4, ice9, ice2]) == 81)
    assert (ice_cream.sweetest_icecream([ice8, ice2, ice2, ice2, ice4, ice8]) == 34)
    # assert (ice_cream.sweetest_icecream([ice4, ice9, ice4, ice3, ice3, ice2, ice5, ice2]), 81)
    # assert (ice_cream.sweetest_icecream([ice8, ice10, ice5]), 34)
    # assert (ice_cream.sweetest_icecream([ice10, ice3, ice2, ice1, ice9]), 81)
    # assert (ice_cream.sweetest_icecream([ice8, ice3, ice4, ice5]), 34)
    # assert (ice_cream.sweetest_icecream([ice10, ice8, ice6, ice7, ice9, ice4]), 81)
    # assert (ice_cream.sweetest_icecream([ice5, ice4, ice6, ice6, ice1]), 33)
    # assert (ice_cream.sweetest_icecream([ice6, ice8, ice2, ice10, ice7, ice10]), 34)
    # assert (ice_cream.sweetest_icecream([ice1, ice9, ice7, ice3]), 81)
    # assert (ice_cream.sweetest_icecream([ice7, ice1, ice9, ice6, ice7, ice10, ice2, ice3]), 81)
    # assert (ice_cream.sweetest_icecream([ice5, ice1, ice7, ice6, ice8, ice1, ice8]), 34)
    # assert (ice_cream.sweetest_icecream([ice10, ice9, ice2, ice4, ice10]), 81)
    # assert (ice_cream.sweetest_icecream([ice3, ice7, ice10]), 17)
    # assert (ice_cream.sweetest_icecream([ice10, ice5, ice4]), 18)
    # assert (ice_cream.sweetest_icecream([ice9, ice2, ice4, ice8, ice3, ice3]), 81)
    # assert (ice_cream.sweetest_icecream([ice6, ice3, ice9, ice8, ice2, ice6]), 81)
    # assert (ice_cream.sweetest_icecream([ice10, ice3]), 17)
    # assert (ice_cream.sweetest_icecream([ice10, ice7, ice5, ice2, ice9]), 81)
    # assert (ice_cream.sweetest_icecream([ice10, ice10, ice4, ice1, ice9]), 81)
    # assert (ice_cream.sweetest_icecream([ice9, ice2, ice6, ice4, ice10, ice3]), 81)
    # assert (ice_cream.sweetest_icecream([ice8, ice10, ice1, ice7, ice8, ice9, ice1]), 81)
    # assert (ice_cream.sweetest_icecream([ice7, ice5, ice3, ice8, ice1, ice9]), 81)
    # assert (ice_cream.sweetest_icecream([ice2, ice6, ice3]), 33)
    # assert (ice_cream.sweetest_icecream([ice6, ice6]), 33)
    # assert (ice_cream.sweetest_icecream([ice9, ice6, ice8, ice3, ice2, ice2]), 81)
    # assert (ice_cream.sweetest_icecream([ice1, ice3, ice3, ice6]), 33)
    # assert (ice_cream.sweetest_icecream([ice8, ice6]), 34)
    # assert (ice_cream.sweetest_icecream([ice1, ice1]), 23)
    # assert (ice_cream.sweetest_icecream([ice4, ice2, ice3, ice9, ice5, ice10, ice6]), 81)
    # assert (ice_cream.sweetest_icecream([ice10, ice8, ice4, ice3, ice9, ice8, ice1, ice10]), 81)
    # assert (ice_cream.sweetest_icecream([ice5, ice8, ice5]), 34)
